services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      # Backend code:
      - ./src/app:/app/app
      # Static uploads folder:
      - ./src/app/static:/app/static

    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:scalpel@db:5432/scalpel_db"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


    # If you didn’t already set CMD in Dockerfile.dev, uncomment:
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: scalpel
      POSTGRES_DB: scalpel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # maps host 5433 → container 5432

  # Uncomment and enable this if/when you want to run tests via Compose.
  # You can also run it with `docker-compose --profile test up` if you add `profiles: ["test"]`
  #
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src/app:/app/app
  #     - ./tests:/app/tests
  #   environment:
  #     DATABASE_URL: "postgresql+asyncpg://postgres:scalpel@db:5432/scalpel_db"
  #   command: ["pytest", "tests/test_endpoints.py", "--disable-warnings", "-s"]

volumes:
  postgres_data:
