version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - ./src/app/static:/app/app/static
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:scalpel@db:5432/scalpel_db"
    # CMD comes from Dockerfile.dev (uvicorn --reload)

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - ./src:/app
      - ./tests:/app/tests
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:scalpel@db:5432/scalpel_db"
    # Override the CMD just for tests:
    command: ["pytest", "tests/test_endpoints.py", "--disable-warnings", "-s"]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: scalpel
      POSTGRES_DB: scalpel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # or "5432:5432" if you don’t need a local Postgres alongside

volumes:
  postgres_data:
