name: Build & Deploy SPA + Lambda

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  ECR_URI: 929423420164.dkr.ecr.eu-west-2.amazonaws.com/scalpel
  LAMBDA_NAME: scalpel-backend
  S3_BUCKET: scalpel-frontend-bucket

jobs:
  deploy_spa:
    name: Build & Deploy SPA to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync build to S3
        run: |
          aws s3 sync frontend/dist \
            s3://${{ env.S3_BUCKET }}/ \
            --region ${{ env.AWS_REGION }}

  deploy_lambda:
    name: Build & Deploy Lambda Container
    runs-on: ubuntu-latest
    needs: deploy_spa

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & push Docker image to ECR
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t "${{ env.ECR_URI }}:latest" \
            .

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name "${{ env.LAMBDA_NAME }}" \
            --image-uri "${{ env.ECR_URI }}:latest"
